<?php

function ccsf_oceia_theme($existing, $type, $theme, $path) {
  return [
    'page_content' => [
      'variables' => ['page_name' => NULL, 'page_vars' => NULL],
    ],
  ];
}

function ccsf_oceia_node_insert($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_node_update($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_node_delete($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_menu_insert($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_menu_update($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_menu_delete($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}