<?php

function ccsf_oceia_theme($existing, $type, $theme, $path) {
  return [
    'page_content' => [
      'variables' => ['page_name' => NULL, 'page_vars' => NULL],
    ],
  ];
}

function ccsf_oceia_node_insert($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_node_update($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_node_delete($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_menu_insert($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_menu_update($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_menu_delete($entity){
  \Drupal::entityManager()->getViewBuilder('node')->resetCache();
}

function ccsf_oceia_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}

function ccsf_oceia_toolbar(){
  $user = \Drupal::currentUser();
  $roles = $user->getRoles();
  $items = []; 
  if(in_array('administrator', $roles) || in_array('dt_staff_user', $roles)){
    $items['ccsf_oceia_toolbar'] = array(
      '#type' => 'toolbar_item',
      'tab' => array(
        '#type' => 'link',
        '#title' => t('Clear cache'),
        '#url' => \Drupal\Core\Url::fromRoute('ccsf_oceia.cc'),
        '#options' => array(
          'attributes' => array(
            'title' => t('Clear cache'),
            'class' => array('toolbar-icon', 'toolbar-item', 'toolbar-icon-system-admin-config'),
          ),
        ),
      )
    );
  }
  return $items;
}



